# Generated by Django 2.2.6 on 2021-01-01 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_id', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Author')),
            ],
        ),
    ]
