# Generated by Django 2.2.6 on 2021-01-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bk_id',
        ),
    ]
